name: smato
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Regular.ttf
      - asset: fonts/Poppins-Bold.ttf
        weight: 700

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  fluttertoast: ^8.0.9
  provider: ^6.1.3
  shared_preferences: ^2.2.2 # versi bisa disesuaikan
  intl: ^0.18.0  # Pastikan versi terbaru atau yang sesuai
  file_picker: ^6.1.1
  permission_handler: ^10.0.0 
  shimmer: ^3.0.0
  google_fonts: ^6.0.0
  lottie: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/reset-password.png
    - assets/images/id-card.png
    - assets/images/options.png
    - assets/images/arrow.png
    - assets/images/inbox.png
    - assets/images/frame.png
    - assets/images/frame.svg
    - assets/images/sma.png
    - assets/images/man.png
    
